services:
    carvalue_db:
        image: postgres:17
        container_name: car-value_db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - carvalue_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    auth_redis:
        image: redis:8
        container_name: car-value-auth_redis
        command: ["redis-server", "--requirepass", "${AUTH_REDIS_PASSWORD}"]
        restart: unless-stopped
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${AUTH_REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    cache_redis:
        image: redis:8
        container_name: car-value-cache_redis
        command: ["redis-server", "--requirepass", "${CACHE_REDIS_PASSWORD}"]
        restart: unless-stopped
        ports:
            - "6380:6379"
        environment:
            REDIS_PASSWORD: ${CACHE_REDIS_PASSWORD}
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${CACHE_REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    
volumes:
    carvalue_data:
        driver: local
