services:
    carvalue_db:
        image: postgres:17
        container_name: car-value_db
        env_file: .env.development
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - carvalue_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    carvalue_data:
        driver: local
