### Login an admin user
# @name login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "StrongPassword123!",
  "clientId": "880f9b05-bba6-48fd-9e40-a7a7b011fa47"
}

###
@accessToken = {{login.response.body.accessToken}}

### Create a new report
POST http://localhost:5001/api/reports
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "price": 19500,
    "make": "Skoda",
    "model": "Kamiq",
    "year": 2022,
    "latitude": 48.8566,
    "longitude": 2.3522,
    "mileage": 8000
}

### Get report by ID
GET http://localhost:5001/api/reports/2

### Get all reports
GET http://localhost:5001/api/reports?offset=0&limit=20&mileage[gte]=20000
Authorization: Bearer {{accessToken}}

### Get estimate from filtered reports
GET http://localhost:5001/api/reports/estimate?make=Volkswagen
Authorization: Bearer {{accessToken}}

### Change report's approval status
PATCH http://localhost:5001/api/reports/1/approval
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "approved": true
}

### Update a report
PUT http://localhost:5001/api/reports/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "price": 9500,
    "make": "Peugeot",
    "model": "308",
    "year": 2017,
    "latitude": 34.0522,
    "longitude": -118.2437,
    "mileage": 106000
}